import { Router } from "express";
import budgetRoutes from "./budgetRoutes.js";
import goalRoutes from "./goalRoutes.js";
import expenseRoutes from "./expenseRoutes.js";
import authRoutes from "./authRoute.js";
import notificationRoutes from "./notificationRoutes.js";
const router = Router();
router.use("/auth", authRoutes);
router.use("/budget", budgetRoutes);
router.use("/goal", goalRoutes);
router.use("/expense", expenseRoutes);
router.use('/notification', notificationRoutes);
export default router;